filename: test
isFile: false
filePath: c://test

test1:
  test2:
    test3: 127.0.0.1

http:
  pool:
    # 连接超时
    connectTimeout: 5000
    #获取连接池中连接超时
    connectionRequestTimeout: 1000
    #每个路由连接数量
    defaultMaxPerRoute: 50
    # /连接池中最大连接数
    maxTotal: 50
    # 服务器返回数据(response)的时间
    socketTimeout: 5000
    #定义不活动的时间（以毫秒为单位）,连接回收
    validateAfterInactivity: 30000

